bind: 0.0.0.0:8080      # address and port to bind on
allow-transfers: true   # allow log file downloads
follow-names: false     # allow tailing of not-yet-existent files
commands: [tail, grep]  # allowed commands
tail-lines: 10          # number of lines to tail initially
wrap-lines: true        # initial line-wrapping state
debug: true

files:
  - '/tmp/log/*'
